POST https://rexdanorum.dk/restjax/api/person
Content-Type: application/json

{
  "fName": "Jonas",
  "lName": "Hansen",
  "phone": "24403013"
}

###

DELETE https://rexdanorum.dk/restjax/api/person/1