POST https://rexdanorum.dk/restjax/api/person
Content-Type: application/json

{
  "fName": "Jens",
  "lName": "Madsen",
  "phone": "12345678"
}

###

DELETE https://rexdanorum.dk/restjax/api/person/1

###

PUT https://rexdanorum.dk/restjax/api/person/3
Content-Type: application/json

{
  "fName": "Helle",
  "lName": "Olsen",
  "phone": "12451263"
}

###

GET https://rexdanorum.dk/restjax/api/person/all